### ISSUE TITLE
ModQueue - TypeError: name() argument 1 must be a unicode character, not str

### ISSUE THREAD

**Issue by notderw** [notderw/Penelope#1]
```
Ignoring exception in on_raw_reaction_add
Traceback (most recent call last):
  File "/home/d/.local/share/virtualenvs/Penelope-B984G3vW/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/d/Penelope/cogs/modqueue.py", line 178, in on_raw_reaction_add
    action = Action.lookup(payload.emoji)
  File "/home/d/Penelope/cogs/modqueue.py", line 141, in lookup
    val = unicodedata.name(emoji.name)
TypeError: name() argument 1 must be a unicode character, not str
```

**Comment by notderw** [comment]
Caused by reactions with emojis that have a length longer than 1 such as 0️⃣  or 1️⃣
